# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6faebd28fccd25fb56fc9b8cafc2399794a1bd51fc8bd350b9347baf10ce6eedb7f7e9d25c42d5bacd02cf9d8832929c9b8e824335848d98c9a099fba056baa

test:
  secret_key_base: 606ebb881161dec9283653e1aa06164c3713e42407fc8eb974e03dafd6522d3f51e5e854cff1468ae541b4b5c760dc0d1fe82970826a7226d39dd8bc7ca4b98b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
